const SET_FROM = 'SET_FROM';
const SET_TO = "SET_TO";
const SHOW_CITY_SELECTOR = "SHOW_CITY_SELECTOR";
const HIDE_CITY_SELECTOR = "HIDE_CITY_SELECTOR";
const TOGGLE_HIGH_SPEED = "TOGGLE_HIGH_SPEED";
const IS_LOADING_CITY_DATA = 'IS_LOADING_CITY_DATA';
const SET_CITY_DATA = "SET_CITY_DATA";
const CITY_DATA_CACHE = "CITY_DATA_CACHE";
const SET_STATION_DIRECTION = "SET_STATION_DIRECTION";
const SHOW_DATE_SELECTOR = 'SHOW_DATE_SELECTOR';
const HIDE_DATE_SELECTOR = 'HIDE_DATE_SELECTOR';
const SET_DEPART_DATE = 'SET_DEPART_DATE';
export {
    SET_FROM,
    SET_TO,
    SHOW_CITY_SELECTOR,
    HIDE_CITY_SELECTOR,
    TOGGLE_HIGH_SPEED,
    IS_LOADING_CITY_DATA,
    SET_CITY_DATA,
    CITY_DATA_CACHE,
    SET_STATION_DIRECTION,
    SHOW_DATE_SELECTOR,
    HIDE_DATE_SELECTOR,
    SET_DEPART_DATE
};