const SET_FROM = 'SET_FROM';
const SET_TO = "SET_TO";
const SET_CITY_SELECTOR_VISIBLE = "SET_CITY_SELECTOR_VISIBLE";
const SET_DATE_SELECTOR_VISIBLE = "SET_DATE_SELECTOR_VISIBLE";
const TOGGLE_HIGH_SPEED = 'TOGGLE_HIGH_SPEED';

export {
    SET_FROM,
    SET_TO
    ,SET_CITY_SELECTOR_VISIBLE,
    SET_DATE_SELECTOR_VISIBLE,
    TOGGLE_HIGH_SPEED,
};