export const SET_FROM = 'SET_FROM';
export const SET_TO = "SET_TO";
export const SHOW_CITY_SELECTOR = "SHOW_CITY_SELECTOR";
export const HIDE_CITY_SELECTOR = "HIDE_CITY_SELECTOR";
export const TOGGLE_HIGH_SPEED = "TOGGLE_HIGH_SPEED";
export const IS_LOADING_CITY_DATA = 'IS_LOADING_CITY_DATA';
export const SET_CITY_DATA = "SET_CITY_DATA";
export const CITY_DATA_CACHE = "CITY_DATA_CACHE";
export const SET_STATION_DIRECTION = "SET_STATION_DIRECTION";
export const SHOW_DATE_SELECTOR = 'SHOW_DATE_SELECTOR';
export const HIDE_DATE_SELECTOR = 'HIDE_DATE_SELECTOR';
export const SET_DEPART_DATE = 'SET_DEPART_DATE';
export const ORDER_DEPART = 'ORDER_DEPART';
export const ORDER_DURATION = 'ORDER_DURATION';
export const SET_ORDER_TYPE = 'SET_ORDER_TYPE';
export const SET_ONLY_TICKETS = "SET_ONLY_TICKETS";
export const SET_TICKET_TYPES = 'SET_TICKET_TYPES';
export const SET_CHECKED_TICKET_TYPES = 'SET_CHECKED_TICKET_TYPES';
export const SET_TRAIN_TYPES = 'SET_TRAIN_TYPES';
export const SET_CHECKED_TRAIN_TYPES = 'SET_CHECKED_TRAIN_TYPES';
export const SET_DEPART_STATION = 'SET_DEPART_STATION';
export const SET_CHECKED_DEPART_STATION = 'SET_CHECKED_DEPART_STATION';
export const SET_ARRIVE_STATION = 'SET_ARRIVE_STATION';
export const SET_CHECKED_ARRIVE_STATION = 'SET_CHECKED_ARRIVE_STATION';
export const SET_DEPART_TIME_START = 'SET_DEPART_TIME_START';
export const SET_DEPART_TIME_END = 'SET_DEPART_TIME_START';
export const SET_ARRIVE_TIME_START = 'SET_ARRIVE_TIME_START';
export const SET_ARRIVE_TIME_END = 'SET_DEPART_TIME_END';
export const SET_IS_FILTER_VISIBLE = 'SET_IS_FILTER_VISIBLE';
export const SHOW_PRICE = 'SHOW_PRICE';
export const SHOW_COUNT = 'SHOW_COUNT';
export const TOGGLE_TICKET_INFO = 'TOGGLE_TICKET_INFO';




