export const SET_FROM = 'SET_FROM';
export const SET_TO = "SET_TO";
export const SHOW_CITY_SELECTOR = "SHOW_CITY_SELECTOR";
export const HIDE_CITY_SELECTOR = "HIDE_CITY_SELECTOR";
export const TOGGLE_HIGH_SPEED = "TOGGLE_HIGH_SPEED";
export const IS_LOADING_CITY_DATA = 'IS_LOADING_CITY_DATA';
export const SET_CITY_DATA = "SET_CITY_DATA";
export const CITY_DATA_CACHE = "CITY_DATA_CACHE";
export const SET_STATION_DIRECTION = "SET_STATION_DIRECTION";
export const SHOW_DATE_SELECTOR = 'SHOW_DATE_SELECTOR';
export const HIDE_DATE_SELECTOR = 'HIDE_DATE_SELECTOR';
export const SET_DEPART_DATE = 'SET_DEPART_DATE';


